JVM G3: jvm/common/bytecode_utils.hpp File Reference
bytecode_utils.hpp File Reference
#include <vector>
#include <cstdint>
#include <stdexcept>
#include "estrutura_dados.hpp"
Functions
int16_t readS2 (const std::vector< u1 > &c, size_t i)
Utilitários para leitura segura do vetor de bytecodes (Code attribute).
int32_t readS4 (const std::vector< u1 > &c, size_t i)
uint16_t readU2 (const std::vector< u1 > &c, size_t i)
Function Documentation
readS2()
int16_t readS2 (const std::vector< u1 > & c, size_t i) inline
Utilitários para leitura segura do vetor de bytecodes (Code attribute).
Durante o disassemble, muitas instruções (como goto ou if_icmpeq) possuem offsets de 2 ou 4 bytes acoplados logo após o opcode. Estas funções garantem a leitura combinando esses bytes matematicamente (Big-Endian) e prevenindo falhas de Out of Bounds caso o arquivo esteja mal-formado.
Definition at line 18 of file bytecode_utils.hpp.
Referenced by disassembleCode().
readS4()
int32_t readS4 (const std::vector< u1 > & c, size_t i) inline
Definition at line 25 of file bytecode_utils.hpp.
Referenced by disassembleCode().
readU2()
uint16_t readU2 (const std::vector< u1 > & c, size_t i) inline
Definition at line 36 of file bytecode_utils.hpp.
Referenced by Exibidor::attributesDisplay(), disassembleCode(), and Exibidor::fieldsDisplay().