JVM G3: Heap Class Reference
Heap Class Reference
#include <heap.hpp>
Public Member Functions
Heap ()
int32_t allocateObject (const class_info *cls, const std::string &class_name)
int32_t allocateArray (u1 element_type, int32_t length)
int32_t allocateRefArray (const std::string &element_class, int32_t length)
bool isNull (int32_t ref) const
HeapObject & object (int32_t ref)
HeapArray & array (int32_t ref)
Value getField (int32_t ref, const std::string &name)
void putField (int32_t ref, const std::string &name, Value value)
int32_t arrayLength (int32_t ref)
Value getElement (int32_t ref, int32_t index)
void setElement (int32_t ref, int32_t index, Value value)
size_t size () const
Private Member Functions
HeapCell & at (int32_t ref)
Static Private Member Functions
static void checkBounds (const HeapArray &a, int32_t index)
static Value defaultFor (u1 element_type)
Private Attributes
std::vector< HeapCell > cells_
Detailed Description
Definition at line 84 of file heap.hpp.
Constructor & Destructor Documentation
Heap()
Heap::Heap () inline
Definition at line 86 of file heap.hpp.
References cells_.
Member Function Documentation
allocateArray()
int32_t Heap::allocateArray (u1 element_type, int32_t length) inline
Definition at line 107 of file heap.hpp.
References HeapCell::ARRAY, HeapCell::array, cells_, defaultFor(), and HeapCell::kind.
allocateObject()
int32_t Heap::allocateObject (const class_info * cls, const std::string & class_name) inline
Definition at line 96 of file heap.hpp.
References cells_, HeapCell::kind, HeapCell::OBJECT, and HeapCell::object.
allocateRefArray()
int32_t Heap::allocateRefArray (const std::string & element_class, int32_t length) inline
Definition at line 121 of file heap.hpp.
References HeapCell::ARRAY, HeapCell::array, cells_, HeapCell::kind, Value::null(), and HeapArray::T_REFERENCE.
array()
HeapArray & Heap::array (int32_t ref) inline
Definition at line 148 of file heap.hpp.
References HeapCell::ARRAY, HeapCell::array, at(), and HeapCell::kind.
Referenced by arrayLength(), getElement(), and setElement().
arrayLength()
int32_t Heap::arrayLength (int32_t ref) inline
Definition at line 171 of file heap.hpp.
References array(), and HeapArray::elements.
at()
HeapCell & Heap::at (int32_t ref) inline private
Definition at line 192 of file heap.hpp.
References cells_.
Referenced by array(), and object().
checkBounds()
void Heap::checkBounds (const HeapArray & a, int32_t index) inline static private
Definition at line 200 of file heap.hpp.
References HeapArray::elements.
Referenced by getElement(), and setElement().
defaultFor()
Value Heap::defaultFor (u1 element_type) inline static private
Definition at line 206 of file heap.hpp.
References Value::fromDouble(), Value::fromFloat(), Value::fromInt(), Value::fromLong(), Value::null(), HeapArray::T_DOUBLE, HeapArray::T_FLOAT, HeapArray::T_LONG, and HeapArray::T_REFERENCE.
Referenced by allocateArray().
getElement()
Value Heap::getElement (int32_t ref, int32_t index) inline
Definition at line 175 of file heap.hpp.
References array(), checkBounds(), and HeapArray::elements.
getField()
Value Heap::getField (int32_t ref, const std::string & name) inline
Definition at line 159 of file heap.hpp.
References HeapObject::fields, and object().
isNull()
bool Heap::isNull (int32_t ref) const inline
Definition at line 139 of file heap.hpp.
object()
HeapObject & Heap::object (int32_t ref) inline
Definition at line 141 of file heap.hpp.
References at(), HeapCell::kind, HeapCell::OBJECT, and HeapCell::object.
Referenced by getField(), and putField().
putField()
void Heap::putField (int32_t ref, const std::string & name, Value value) inline
Definition at line 163 of file heap.hpp.
References HeapObject::fields, and object().
setElement()
void Heap::setElement (int32_t ref, int32_t index, Value value) inline
Definition at line 181 of file heap.hpp.
References array(), checkBounds(), and HeapArray::elements.
size()
size_t Heap::size () const inline
Definition at line 187 of file heap.hpp.
References cells_.
Member Data Documentation
cells_
std::vector<HeapCell> Heap::cells_ private
Definition at line 190 of file heap.hpp.
Referenced by allocateArray(), allocateObject(), allocateRefArray(), at(), Heap(), and size().
The documentation for this class was generated from the following file:
jvm/heap/heap.hpp