JVM G3: Interpreter Class Reference
Interpreter Class Reference
#include <interpreter.hpp>
Public Member Functions
Interpreter (ClassLoader &loader, FrameStack &frame_stack, Heap &heap)
void execute (const class_info &cls, const method_info &method)
void run ()
bool halted () const
void halt ()
Private Member Functions
void buildDispatchTable ()
Frame & currentFrame ()
u1 fetchU1 ()
u2 fetchU2 ()
u4 fetchU4 ()
int8_t fetchS1 ()
int16_t fetchS2 ()
int32_t fetchS4 ()
void branch (int32_t offset)
const code_attribute * findCode (const method_info &method) const
void op_nop ()
void op_aconst_null ()
void op_iconst (int32_t value)
void op_iconst_m1 ()
void op_iconst_0 ()
void op_iconst_1 ()
void op_iconst_2 ()
void op_iconst_3 ()
void op_iconst_4 ()
void op_iconst_5 ()
void op_lconst_0 ()
void op_lconst_1 ()
void op_fconst_0 ()
void op_fconst_1 ()
void op_fconst_2 ()
void op_dconst_0 ()
void op_dconst_1 ()
void op_bipush ()
void op_sipush ()
void op_ldc ()
void op_ldc_w ()
void op_ldc2_w ()
void op_iload ()
void op_iload_0 ()
void op_iload_1 ()
void op_iload_2 ()
void op_iload_3 ()
void op_lload ()
void op_lload_0 ()
void op_lload_1 ()
void op_lload_2 ()
void op_lload_3 ()
void op_fload ()
void op_fload_0 ()
void op_fload_1 ()
void op_fload_2 ()
void op_fload_3 ()
void op_dload ()
void op_dload_0 ()
void op_dload_1 ()
void op_dload_2 ()
void op_dload_3 ()
void op_aload ()
void op_aload_0 ()
void op_aload_1 ()
void op_aload_2 ()
void op_aload_3 ()
void op_istore ()
void op_istore_0 ()
void op_istore_1 ()
void op_istore_2 ()
void op_istore_3 ()
void op_lstore ()
void op_lstore_0 ()
void op_lstore_1 ()
void op_lstore_2 ()
void op_lstore_3 ()
void op_fstore ()
void op_fstore_0 ()
void op_fstore_1 ()
void op_fstore_2 ()
void op_fstore_3 ()
void op_dstore ()
void op_dstore_0 ()
void op_dstore_1 ()
void op_dstore_2 ()
void op_dstore_3 ()
void op_astore ()
void op_astore_0 ()
void op_astore_1 ()
void op_astore_2 ()
void op_astore_3 ()
void op_iadd ()
void op_isub ()
void op_imul ()
void op_idiv ()
void op_irem ()
void op_ineg ()
void op_iand ()
void op_ior ()
void op_ixor ()
void op_ishl ()
void op_ishr ()
void op_iushr ()
void op_iinc ()
void op_ladd ()
void op_lsub ()
void op_lmul ()
void op_ldiv ()
void op_lrem ()
void op_lneg ()
void op_land ()
void op_lor ()
void op_lxor ()
void op_lshl ()
void op_lshr ()
void op_lushr ()
void op_lcmp ()
void op_fadd ()
void op_fsub ()
void op_fmul ()
void op_fdiv ()
void op_frem ()
void op_fneg ()
void op_dadd ()
void op_dsub ()
void op_dmul ()
void op_ddiv ()
void op_drem ()
void op_dneg ()
void op_fcmpl ()
void op_fcmpg ()
void op_dcmpl ()
void op_dcmpg ()
void op_i2l ()
void op_i2f ()
void op_i2d ()
void op_l2i ()
void op_l2f ()
void op_l2d ()
void op_f2i ()
void op_f2l ()
void op_f2d ()
void op_d2i ()
void op_d2l ()
void op_d2f ()
void op_i2b ()
void op_i2c ()
void op_i2s ()
void op_pop ()
void op_pop2 ()
void op_dup ()
void op_dup_x1 ()
void op_dup_x2 ()
void op_dup2 ()
void op_swap ()
void op_ifeq ()
void op_ifne ()
void op_iflt ()
void op_ifge ()
void op_ifgt ()
void op_ifle ()
void op_if_icmpeq ()
void op_if_icmpne ()
void op_if_icmplt ()
void op_if_icmpge ()
void op_if_icmpgt ()
void op_if_icmple ()
void op_ifnull ()
void op_ifnonnull ()
void op_if_acmpeq ()
void op_if_acmpne ()
void op_goto ()
void op_goto_w ()
void op_tableswitch ()
void op_lookupswitch ()
void op_invokestatic ()
void op_invokespecial ()
void op_invokevirtual ()
void op_invokeinterface ()
void op_return ()
void op_ireturn ()
void op_lreturn ()
void op_freturn ()
void op_dreturn ()
void op_areturn ()
void op_getstatic ()
void op_putstatic ()
void op_getfield ()
void op_putfield ()
void op_new ()
void op_newarray ()
void op_anewarray ()
void op_arraylength ()
void op_iaload ()
void op_iastore ()
void op_laload ()
void op_lastore ()
void op_faload ()
void op_fastore ()
void op_daload ()
void op_dastore ()
void op_aaload ()
void op_aastore ()
void op_baload ()
void op_bastore ()
void op_caload ()
void op_castore ()
void op_saload ()
void op_sastore ()
void op_athrow ()
void op_checkcast ()
void op_instanceof ()
void simulatePrint (const std::string &method_name, const std::string &descriptor)
Private Attributes
ClassLoader & loader_
FrameStack & frame_stack_
Heap & heap_
bool halted_ = false
std::unordered_map< uint8_t, std::function< void()> > dispatch_table_
Detailed Description
Definition at line 23 of file interpreter.hpp.
Constructor & Destructor Documentation
Interpreter()
Interpreter::Interpreter (ClassLoader & loader, FrameStack & frame_stack, Heap & heap)
Definition at line 15 of file interpreter.cpp.
References buildDispatchTable(), frame_stack_, heap_, and loader_.
Member Function Documentation
branch()
void Interpreter::branch (int32_t offset) private
Definition at line 242 of file interpreter.cpp.
References currentFrame(), and Frame::pc.
Referenced by op_if_acmpeq(), op_if_acmpne(), op_if_icmpeq(), op_if_icmpge(), op_if_icmpgt(), op_if_icmple(), op_if_icmplt(), op_if_icmpne(), op_ifeq(), op_ifge(), op_ifgt(), op_ifle(), op_iflt(), op_ifne(), op_ifnonnull(), and op_ifnull().
buildDispatchTable()
void Interpreter::buildDispatchTable () private
Definition at line 21 of file interpreter.cpp.
References dispatch_table_, op_aaload(), op_aastore(), op_aconst_null(), op_aload(), op_aload_0(), op_aload_1(), op_aload_2(), op_aload_3(), op_anewarray(), op_areturn(), op_arraylength(), op_astore(), op_astore_0(), op_astore_1(), op_astore_2(), op_astore_3(), op_athrow(), op_baload(), op_bastore(), op_bipush(), op_caload(), op_castore(), op_checkcast(), op_d2f(), op_d2i(), op_d2l(), op_dadd(), op_daload(), op_dastore(), op_dcmpg(), op_dcmpl(), op_dconst_0(), op_dconst_1(), op_ddiv(), op_dload(), op_dload_0(), op_dload_1(), op_dload_2(), op_dload_3(), op_dmul(), op_dneg(), op_drem(), op_dreturn(), op_dstore(), op_dstore_0(), op_dstore_1(), op_dstore_2(), op_dstore_3(), op_dsub(), op_dup(), op_dup2(), op_dup_x1(), op_dup_x2(), op_f2d(), op_f2i(), op_f2l(), op_fadd(), op_faload(), op_fastore(), op_fcmpg(), op_fcmpl(), op_fconst_0(), op_fconst_1(), op_fconst_2(), op_fdiv(), op_fload(), op_fload_0(), op_fload_1(), op_fload_2(), op_fload_3(), op_fmul(), op_fneg(), op_frem(), op_freturn(), op_fstore(), op_fstore_0(), op_fstore_1(), op_fstore_2(), op_fstore_3(), op_fsub(), op_getfield(), op_getstatic(), op_goto(), op_goto_w(), op_i2b(), op_i2c(), op_i2d(), op_i2f(), op_i2l(), op_i2s(), op_iadd(), op_iaload(), op_iand(), op_iastore(), op_iconst_0(), op_iconst_1(), op_iconst_2(), op_iconst_3(), op_iconst_4(), op_iconst_5(), op_iconst_m1(), op_idiv(), op_if_acmpeq(), op_if_acmpne(), op_if_icmpeq(), op_if_icmpge(), op_if_icmpgt(), op_if_icmple(), op_if_icmplt(), op_if_icmpne(), op_ifeq(), op_ifge(), op_ifgt(), op_ifle(), op_iflt(), op_ifne(), op_ifnonnull(), op_ifnull(), op_iinc(), op_iload(), op_iload_0(), op_iload_1(), op_iload_2(), op_iload_3(), op_imul(), op_ineg(), op_instanceof(), op_invokeinterface(), op_invokespecial(), op_invokestatic(), op_invokevirtual(), op_ior(), op_irem(), op_ireturn(), op_ishl(), op_ishr(), op_istore(), op_istore_0(), op_istore_1(), op_istore_2(), op_istore_3(), op_isub(), op_iushr(), op_ixor(), op_l2d(), op_l2f(), op_l2i(), op_ladd(), op_laload(), op_land(), op_lastore(), op_lcmp(), op_lconst_0(), op_lconst_1(), op_ldc(), op_ldc2_w(), op_ldc_w(), op_ldiv(), op_lload(), op_lload_0(), op_lload_1(), op_lload_2(), op_lload_3(), op_lmul(), op_lneg(), op_lookupswitch(), op_lor(), op_lrem(), op_lreturn(), op_lshl(), op_lshr(), op_lstore(), op_lstore_0(), op_lstore_1(), op_lstore_2(), op_lstore_3(), op_lsub(), op_lushr(), op_lxor(), op_new(), op_newarray(), op_nop(), op_pop(), op_pop2(), op_putfield(), op_putstatic(), op_return(), op_saload(), op_sastore(), op_sipush(), op_swap(), and op_tableswitch().
Referenced by Interpreter().
currentFrame()
Frame & Interpreter::currentFrame () private
Definition at line 217 of file interpreter.cpp.
References frame_stack_.
Referenced by branch(), fetchU1(), op_aaload(), op_aastore(), op_aconst_null(), op_aload(), op_aload_0(), op_aload_1(), op_aload_2(), op_aload_3(), op_anewarray(), op_arraylength(), op_astore(), op_astore_0(), op_astore_1(), op_astore_2(), op_astore_3(), op_athrow(), op_baload(), op_bastore(), op_bipush(), op_caload(), op_castore(), op_checkcast(), op_d2f(), op_d2i(), op_d2l(), op_dadd(), op_daload(), op_dastore(), op_dcmpg(), op_dcmpl(), op_dconst_0(), op_dconst_1(), op_ddiv(), op_dload(), op_dload_0(), op_dload_1(), op_dload_2(), op_dload_3(), op_dmul(), op_dneg(), op_drem(), op_dstore(), op_dstore_0(), op_dstore_1(), op_dstore_2(), op_dstore_3(), op_dsub(), op_dup(), op_dup2(), op_dup_x1(), op_dup_x2(), op_f2d(), op_f2i(), op_f2l(), op_fadd(), op_faload(), op_fastore(), op_fcmpg(), op_fcmpl(), op_fconst_0(), op_fconst_1(), op_fconst_2(), op_fdiv(), op_fload(), op_fload_0(), op_fload_1(), op_fload_2(), op_fload_3(), op_fmul(), op_fneg(), op_frem(), op_fstore(), op_fstore_0(), op_fstore_1(), op_fstore_2(), op_fstore_3(), op_fsub(), op_getfield(), op_getstatic(), op_goto(), op_goto_w(), op_i2b(), op_i2c(), op_i2d(), op_i2f(), op_i2l(), op_i2s(), op_iadd(), op_iaload(), op_iand(), op_iastore(), op_iconst(), op_idiv(), op_if_acmpeq(), op_if_acmpne(), op_if_icmpeq(), op_if_icmpge(), op_if_icmpgt(), op_if_icmple(), op_if_icmplt(), op_if_icmpne(), op_ifeq(), op_ifge(), op_ifgt(), op_ifle(), op_iflt(), op_ifne(), op_ifnonnull(), op_ifnull(), op_iinc(), op_iload(), op_iload_0(), op_iload_1(), op_iload_2(), op_iload_3(), op_imul(), op_ineg(), op_instanceof(), op_invokeinterface(), op_invokespecial(), op_invokestatic(), op_invokevirtual(), op_ior(), op_irem(), op_ishl(), op_ishr(), op_istore(), op_istore_0(), op_istore_1(), op_istore_2(), op_istore_3(), op_isub(), op_iushr(), op_ixor(), op_l2d(), op_l2f(), op_l2i(), op_ladd(), op_laload(), op_land(), op_lastore(), op_lcmp(), op_lconst_0(), op_lconst_1(), op_ldc(), op_ldc2_w(), op_ldc_w(), op_ldiv(), op_lload(), op_lload_0(), op_lload_1(), op_lload_2(), op_lload_3(), op_lmul(), op_lneg(), op_lookupswitch(), op_lor(), op_lrem(), op_lshl(), op_lshr(), op_lstore(), op_lstore_0(), op_lstore_1(), op_lstore_2(), op_lstore_3(), op_lsub(), op_lushr(), op_lxor(), op_new(), op_newarray(), op_pop(), op_pop2(), op_putfield(), op_putstatic(), op_saload(), op_sastore(), op_sipush(), op_swap(), op_tableswitch(), and simulatePrint().
execute()
void Interpreter::execute (const class_info & cls, const method_info & method)
Definition at line 180 of file interpreter.cpp.
References Frame::cls, Frame::code, findCode(), frame_stack_, Value::fromInt(), Frame::locals, code_attribute::max_locals, Frame::method, Frame::pc, and run().
Referenced by main().
fetchS1()
int8_t Interpreter::fetchS1 () private
Definition at line 238 of file interpreter.cpp.
References fetchU1().
Referenced by op_bipush(), and op_iinc().
fetchS2()
int16_t Interpreter::fetchS2 () private
Definition at line 239 of file interpreter.cpp.
References fetchU2().
Referenced by op_goto(), op_if_acmpeq(), op_if_acmpne(), op_if_icmpeq(), op_if_icmpge(), op_if_icmpgt(), op_if_icmple(), op_if_icmplt(), op_if_icmpne(), op_ifeq(), op_ifge(), op_ifgt(), op_ifle(), op_iflt(), op_ifne(), op_ifnonnull(), op_ifnull(), and op_sipush().
fetchS4()
int32_t Interpreter::fetchS4 () private
Definition at line 240 of file interpreter.cpp.
References fetchU4().
Referenced by op_goto_w(), op_lookupswitch(), and op_tableswitch().
fetchU1()
u1 Interpreter::fetchU1 () private
Definition at line 221 of file interpreter.cpp.
References code_attribute::code, Frame::code, currentFrame(), and Frame::pc.
Referenced by fetchS1(), fetchU2(), op_aload(), op_astore(), op_dload(), op_dstore(), op_fload(), op_fstore(), op_iinc(), op_iload(), op_invokeinterface(), op_istore(), op_ldc(), op_lload(), op_lstore(), op_newarray(), and run().
fetchU2()
u2 Interpreter::fetchU2 () private
Definition at line 226 of file interpreter.cpp.
References fetchU1().
Referenced by fetchS2(), fetchU4(), op_anewarray(), op_checkcast(), op_getfield(), op_getstatic(), op_instanceof(), op_invokeinterface(), op_invokespecial(), op_invokestatic(), op_invokevirtual(), op_ldc2_w(), op_ldc_w(), op_new(), op_putfield(), and op_putstatic().
fetchU4()
u4 Interpreter::fetchU4 () private
Definition at line 232 of file interpreter.cpp.
References fetchU2().
Referenced by fetchS4().
findCode()
const code_attribute * Interpreter::findCode (const method_info & method) const private
Definition at line 249 of file interpreter.cpp.
References method_info::attributes, and attribute_info::code_data.
Referenced by execute().
halt()
void Interpreter::halt () inline
Definition at line 34 of file interpreter.hpp.
References halted_.
halted()
bool Interpreter::halted () const inline
Definition at line 33 of file interpreter.hpp.
References halted_.
op_aaload()
void Interpreter::op_aaload () private
Definition at line 1734 of file interpreter.cpp.
References currentFrame(), Value::data, heap_, Value::i, Frame::pop(), Frame::push(), and Value::ref.
Referenced by buildDispatchTable().
op_aastore()
void Interpreter::op_aastore () private
Definition at line 1744 of file interpreter.cpp.
References currentFrame(), Value::data, heap_, Value::i, Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_aconst_null()
void Interpreter::op_aconst_null () private
Definition at line 262 of file interpreter.cpp.
References currentFrame(), Value::null(), and Frame::push().
Referenced by buildDispatchTable().
op_aload()
void Interpreter::op_aload () private
Definition at line 771 of file interpreter.cpp.
References currentFrame(), fetchU1(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_aload_0()
void Interpreter::op_aload_0 () private
Definition at line 767 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_aload_1()
void Interpreter::op_aload_1 () private
Definition at line 768 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_aload_2()
void Interpreter::op_aload_2 () private
Definition at line 769 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_aload_3()
void Interpreter::op_aload_3 () private
Definition at line 770 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_anewarray()
void Interpreter::op_anewarray () private
Definition at line 1633 of file interpreter.cpp.
References classNameFromConstantPool(), Frame::cls, currentFrame(), Value::data, fetchU2(), Value::fromRef(), heap_, Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_areturn()
void Interpreter::op_areturn () private
Definition at line 1260 of file interpreter.cpp.
References frame_stack_.
Referenced by buildDispatchTable().
op_arraylength()
void Interpreter::op_arraylength () private
Definition at line 1644 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), heap_, Frame::pop(), Frame::push(), and Value::ref.
Referenced by buildDispatchTable().
op_astore()
void Interpreter::op_astore () private
Definition at line 795 of file interpreter.cpp.
References currentFrame(), fetchU1(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_astore_0()
void Interpreter::op_astore_0 () private
Definition at line 791 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_astore_1()
void Interpreter::op_astore_1 () private
Definition at line 792 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_astore_2()
void Interpreter::op_astore_2 () private
Definition at line 793 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_astore_3()
void Interpreter::op_astore_3 () private
Definition at line 794 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_athrow()
void Interpreter::op_athrow () private
Definition at line 1850 of file interpreter.cpp.
References currentFrame(), Value::data, heap_, Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_baload()
void Interpreter::op_baload () private
Definition at line 1756 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), heap_, Value::i, Frame::pop(), Frame::push(), and Value::ref.
Referenced by buildDispatchTable().
op_bastore()
void Interpreter::op_bastore () private
Definition at line 1765 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), heap_, Value::i, Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_bipush()
void Interpreter::op_bipush () private
Definition at line 288 of file interpreter.cpp.
References currentFrame(), fetchS1(), Value::fromInt(), and Frame::push().
Referenced by buildDispatchTable().
op_caload()
void Interpreter::op_caload () private
Definition at line 1777 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), heap_, Value::i, Frame::pop(), Frame::push(), and Value::ref.
Referenced by buildDispatchTable().
op_castore()
void Interpreter::op_castore () private
Definition at line 1786 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), heap_, Value::i, Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_checkcast()
void Interpreter::op_checkcast () private
Definition at line 1860 of file interpreter.cpp.
References classNameFromConstantPool(), Frame::cls, currentFrame(), Value::data, fetchU2(), heap_, loader_, Value::ref, and Frame::top().
Referenced by buildDispatchTable().
op_d2f()
void Interpreter::op_d2f () private
Definition at line 1039 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::fromFloat(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_d2i()
void Interpreter::op_d2i () private
Definition at line 1027 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::fromInt(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_d2l()
void Interpreter::op_d2l () private
Definition at line 1033 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::fromLong(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_dadd()
void Interpreter::op_dadd () private
Definition at line 620 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::fromDouble(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_daload()
void Interpreter::op_daload () private
Definition at line 1714 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromDouble(), heap_, Value::i, Frame::pop(), Frame::push(), and Value::ref.
Referenced by buildDispatchTable().
op_dastore()
void Interpreter::op_dastore () private
Definition at line 1723 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::fromDouble(), heap_, Value::i, Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_dcmpg()
void Interpreter::op_dcmpg () private
Definition at line 725 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::fromInt(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_dcmpl()
void Interpreter::op_dcmpl () private
Definition at line 711 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::fromInt(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_dconst_0()
void Interpreter::op_dconst_0 () private
Definition at line 285 of file interpreter.cpp.
References currentFrame(), Value::fromDouble(), and Frame::push().
Referenced by buildDispatchTable().
op_dconst_1()
void Interpreter::op_dconst_1 () private
Definition at line 286 of file interpreter.cpp.
References currentFrame(), Value::fromDouble(), and Frame::push().
Referenced by buildDispatchTable().
op_ddiv()
void Interpreter::op_ddiv () private
Definition at line 647 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::fromDouble(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_dload()
void Interpreter::op_dload () private
Definition at line 765 of file interpreter.cpp.
References currentFrame(), fetchU1(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_dload_0()
void Interpreter::op_dload_0 () private
Definition at line 761 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_dload_1()
void Interpreter::op_dload_1 () private
Definition at line 762 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_dload_2()
void Interpreter::op_dload_2 () private
Definition at line 763 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_dload_3()
void Interpreter::op_dload_3 () private
Definition at line 764 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_dmul()
void Interpreter::op_dmul () private
Definition at line 638 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::fromDouble(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_dneg()
void Interpreter::op_dneg () private
Definition at line 656 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::fromDouble(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_drem()
void Interpreter::op_drem () private
Definition at line 664 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::fromDouble(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_dreturn()
void Interpreter::op_dreturn () private
Definition at line 1253 of file interpreter.cpp.
References frame_stack_.
Referenced by buildDispatchTable().
op_dstore()
void Interpreter::op_dstore () private
Definition at line 789 of file interpreter.cpp.
References currentFrame(), fetchU1(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_dstore_0()
void Interpreter::op_dstore_0 () private
Definition at line 785 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_dstore_1()
void Interpreter::op_dstore_1 () private
Definition at line 786 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_dstore_2()
void Interpreter::op_dstore_2 () private
Definition at line 787 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_dstore_3()
void Interpreter::op_dstore_3 () private
Definition at line 788 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_dsub()
void Interpreter::op_dsub () private
Definition at line 629 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::fromDouble(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_dup()
void Interpreter::op_dup () private
Definition at line 869 of file interpreter.cpp.
References currentFrame(), Frame::push(), and Frame::top().
Referenced by buildDispatchTable().
op_dup2()
void Interpreter::op_dup2 () private
Definition at line 913 of file interpreter.cpp.
References currentFrame(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_dup_x1()
void Interpreter::op_dup_x1 () private
Definition at line 877 of file interpreter.cpp.
References currentFrame(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_dup_x2()
void Interpreter::op_dup_x2 () private
Definition at line 890 of file interpreter.cpp.
References currentFrame(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_f2d()
void Interpreter::op_f2d () private
Definition at line 1021 of file interpreter.cpp.
References currentFrame(), Value::data, Value::f, Value::fromDouble(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_f2i()
void Interpreter::op_f2i () private
Definition at line 1009 of file interpreter.cpp.
References currentFrame(), Value::data, Value::f, Value::fromInt(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_f2l()
void Interpreter::op_f2l () private
Definition at line 1015 of file interpreter.cpp.
References currentFrame(), Value::data, Value::f, Value::fromLong(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_fadd()
void Interpreter::op_fadd () private
Definition at line 566 of file interpreter.cpp.
References currentFrame(), Value::data, Value::f, Value::fromFloat(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_faload()
void Interpreter::op_faload () private
Definition at line 1694 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromFloat(), heap_, Value::i, Frame::pop(), Frame::push(), and Value::ref.
Referenced by buildDispatchTable().
op_fastore()
void Interpreter::op_fastore () private
Definition at line 1703 of file interpreter.cpp.
References currentFrame(), Value::data, Value::f, Value::fromFloat(), heap_, Value::i, Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_fcmpg()
void Interpreter::op_fcmpg () private
Definition at line 697 of file interpreter.cpp.
References currentFrame(), Value::data, Value::f, Value::fromInt(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_fcmpl()
void Interpreter::op_fcmpl () private
Definition at line 683 of file interpreter.cpp.
References currentFrame(), Value::data, Value::f, Value::fromInt(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_fconst_0()
void Interpreter::op_fconst_0 () private
Definition at line 281 of file interpreter.cpp.
References currentFrame(), Value::fromFloat(), and Frame::push().
Referenced by buildDispatchTable().
op_fconst_1()
void Interpreter::op_fconst_1 () private
Definition at line 282 of file interpreter.cpp.
References currentFrame(), Value::fromFloat(), and Frame::push().
Referenced by buildDispatchTable().
op_fconst_2()
void Interpreter::op_fconst_2 () private
Definition at line 283 of file interpreter.cpp.
References currentFrame(), Value::fromFloat(), and Frame::push().
Referenced by buildDispatchTable().
op_fdiv()
void Interpreter::op_fdiv () private
Definition at line 593 of file interpreter.cpp.
References currentFrame(), Value::data, Value::f, Value::fromFloat(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_fload()
void Interpreter::op_fload () private
Definition at line 759 of file interpreter.cpp.
References currentFrame(), fetchU1(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_fload_0()
void Interpreter::op_fload_0 () private
Definition at line 755 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_fload_1()
void Interpreter::op_fload_1 () private
Definition at line 756 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_fload_2()
void Interpreter::op_fload_2 () private
Definition at line 757 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_fload_3()
void Interpreter::op_fload_3 () private
Definition at line 758 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_fmul()
void Interpreter::op_fmul () private
Definition at line 584 of file interpreter.cpp.
References currentFrame(), Value::data, Value::f, Value::fromFloat(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_fneg()
void Interpreter::op_fneg () private
Definition at line 602 of file interpreter.cpp.
References currentFrame(), Value::data, Value::f, Value::fromFloat(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_frem()
void Interpreter::op_frem () private
Definition at line 610 of file interpreter.cpp.
References currentFrame(), Value::data, Value::f, Value::fromFloat(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_freturn()
void Interpreter::op_freturn () private
Definition at line 1246 of file interpreter.cpp.
References frame_stack_.
Referenced by buildDispatchTable().
op_fstore()
void Interpreter::op_fstore () private
Definition at line 783 of file interpreter.cpp.
References currentFrame(), fetchU1(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_fstore_0()
void Interpreter::op_fstore_0 () private
Definition at line 779 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_fstore_1()
void Interpreter::op_fstore_1 () private
Definition at line 780 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_fstore_2()
void Interpreter::op_fstore_2 () private
Definition at line 781 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_fstore_3()
void Interpreter::op_fstore_3 () private
Definition at line 782 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_fsub()
void Interpreter::op_fsub () private
Definition at line 575 of file interpreter.cpp.
References currentFrame(), Value::data, Value::f, Value::fromFloat(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_getfield()
void Interpreter::op_getfield () private
Definition at line 1454 of file interpreter.cpp.
References Frame::cls, class_info::constant_pool, cp_info::container, currentFrame(), Value::data, fetchU2(), cp_info::Fieldref, heap_, cp_info::name_and_type_index, cp_info::name_index, cp_info::NameAndType, Frame::pop(), Frame::push(), Value::ref, and utf8FromConstantPool().
Referenced by buildDispatchTable().
op_getstatic()
void Interpreter::op_getstatic () private
Definition at line 1486 of file interpreter.cpp.
References cp_info::class_index, classNameFromConstantPool(), Frame::cls, class_info::constant_pool, cp_info::container, currentFrame(), cp_info::descriptor_index, fetchU2(), cp_info::Fieldref, Value::fromDouble(), Value::fromFloat(), Value::fromInt(), Value::fromLong(), loader_, cp_info::name_and_type_index, cp_info::name_index, cp_info::NameAndType, Value::null(), Frame::push(), and utf8FromConstantPool().
Referenced by buildDispatchTable().
op_goto()
void Interpreter::op_goto () private
Definition at line 381 of file interpreter.cpp.
References currentFrame(), fetchS2(), and Frame::pc.
Referenced by buildDispatchTable().
op_goto_w()
void Interpreter::op_goto_w () private
Definition at line 1182 of file interpreter.cpp.
References currentFrame(), fetchS4(), and Frame::pc.
Referenced by buildDispatchTable().
op_i2b()
void Interpreter::op_i2b () private
Definition at line 1045 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_i2c()
void Interpreter::op_i2c () private
Definition at line 1051 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_i2d()
void Interpreter::op_i2d () private
Definition at line 985 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromDouble(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_i2f()
void Interpreter::op_i2f () private
Definition at line 979 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromFloat(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_i2l()
void Interpreter::op_i2l () private
Definition at line 973 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_i2s()
void Interpreter::op_i2s () private
Definition at line 1057 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_iadd()
void Interpreter::op_iadd () private
Definition at line 298 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_iaload()
void Interpreter::op_iaload () private
Definition at line 1653 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), heap_, Value::i, Frame::pop(), Frame::push(), and Value::ref.
Referenced by buildDispatchTable().
op_iand()
void Interpreter::op_iand () private
Definition at line 797 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_iastore()
void Interpreter::op_iastore () private
Definition at line 1663 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), heap_, Value::i, Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_iconst()
void Interpreter::op_iconst (int32_t value) private
Definition at line 266 of file interpreter.cpp.
References currentFrame(), Value::fromInt(), and Frame::push().
Referenced by op_iconst_0(), op_iconst_1(), op_iconst_2(), op_iconst_3(), op_iconst_4(), op_iconst_5(), and op_iconst_m1().
op_iconst_0()
void Interpreter::op_iconst_0 () private
Definition at line 271 of file interpreter.cpp.
References op_iconst().
Referenced by buildDispatchTable().
op_iconst_1()
void Interpreter::op_iconst_1 () private
Definition at line 272 of file interpreter.cpp.
References op_iconst().
Referenced by buildDispatchTable().
op_iconst_2()
void Interpreter::op_iconst_2 () private
Definition at line 273 of file interpreter.cpp.
References op_iconst().
Referenced by buildDispatchTable().
op_iconst_3()
void Interpreter::op_iconst_3 () private
Definition at line 274 of file interpreter.cpp.
References op_iconst().
Referenced by buildDispatchTable().
op_iconst_4()
void Interpreter::op_iconst_4 () private
Definition at line 275 of file interpreter.cpp.
References op_iconst().
Referenced by buildDispatchTable().
op_iconst_5()
void Interpreter::op_iconst_5 () private
Definition at line 276 of file interpreter.cpp.
References op_iconst().
Referenced by buildDispatchTable().
op_iconst_m1()
void Interpreter::op_iconst_m1 () private
Definition at line 270 of file interpreter.cpp.
References op_iconst().
Referenced by buildDispatchTable().
op_idiv()
void Interpreter::op_idiv () private
Definition at line 319 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_if_acmpeq()
void Interpreter::op_if_acmpeq () private
Definition at line 1165 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_if_acmpne()
void Interpreter::op_if_acmpne () private
Definition at line 1173 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_if_icmpeq()
void Interpreter::op_if_icmpeq () private
Definition at line 1103 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Value::i, and Frame::pop().
Referenced by buildDispatchTable().
op_if_icmpge()
void Interpreter::op_if_icmpge () private
Definition at line 1127 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Value::i, and Frame::pop().
Referenced by buildDispatchTable().
op_if_icmpgt()
void Interpreter::op_if_icmpgt () private
Definition at line 1135 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Value::i, and Frame::pop().
Referenced by buildDispatchTable().
op_if_icmple()
void Interpreter::op_if_icmple () private
Definition at line 1143 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Value::i, and Frame::pop().
Referenced by buildDispatchTable().
op_if_icmplt()
void Interpreter::op_if_icmplt () private
Definition at line 1119 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Value::i, and Frame::pop().
Referenced by buildDispatchTable().
op_if_icmpne()
void Interpreter::op_if_icmpne () private
Definition at line 1111 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Value::i, and Frame::pop().
Referenced by buildDispatchTable().
op_ifeq()
void Interpreter::op_ifeq () private
Definition at line 1066 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Value::i, and Frame::pop().
Referenced by buildDispatchTable().
op_ifge()
void Interpreter::op_ifge () private
Definition at line 1084 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Value::i, and Frame::pop().
Referenced by buildDispatchTable().
op_ifgt()
void Interpreter::op_ifgt () private
Definition at line 1090 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Value::i, and Frame::pop().
Referenced by buildDispatchTable().
op_ifle()
void Interpreter::op_ifle () private
Definition at line 1096 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Value::i, and Frame::pop().
Referenced by buildDispatchTable().
op_iflt()
void Interpreter::op_iflt () private
Definition at line 1078 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Value::i, and Frame::pop().
Referenced by buildDispatchTable().
op_ifne()
void Interpreter::op_ifne () private
Definition at line 1072 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), Value::i, and Frame::pop().
Referenced by buildDispatchTable().
op_ifnonnull()
void Interpreter::op_ifnonnull () private
Definition at line 1158 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), heap_, Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_ifnull()
void Interpreter::op_ifnull () private
Definition at line 1152 of file interpreter.cpp.
References branch(), currentFrame(), Value::data, fetchS2(), heap_, Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_iinc()
void Interpreter::op_iinc () private
Definition at line 362 of file interpreter.cpp.
References currentFrame(), fetchS1(), fetchU1(), and Frame::locals.
Referenced by buildDispatchTable().
op_iload()
void Interpreter::op_iload () private
Definition at line 345 of file interpreter.cpp.
References currentFrame(), fetchU1(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_iload_0()
void Interpreter::op_iload_0 () private
Definition at line 340 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_iload_1()
void Interpreter::op_iload_1 () private
Definition at line 341 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_iload_2()
void Interpreter::op_iload_2 () private
Definition at line 342 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_iload_3()
void Interpreter::op_iload_3 () private
Definition at line 343 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_imul()
void Interpreter::op_imul () private
Definition at line 312 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_ineg()
void Interpreter::op_ineg () private
Definition at line 335 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_instanceof()
void Interpreter::op_instanceof () private
Definition at line 1877 of file interpreter.cpp.
References classNameFromConstantPool(), Frame::cls, currentFrame(), Value::data, fetchU2(), Value::fromInt(), heap_, loader_, Frame::pop(), Frame::push(), and Value::ref.
Referenced by buildDispatchTable().
op_invokeinterface()
void Interpreter::op_invokeinterface () private
Definition at line 1438 of file interpreter.cpp.
References cp_info::class_index, classNameFromConstantPool(), Frame::cls, class_info::constant_pool, cp_info::container, currentFrame(), cp_info::descriptor_index, fetchU1(), fetchU2(), frame_stack_, heap_, cp_info::InterfaceMethodref, loader_, cp_info::name_and_type_index, cp_info::name_index, cp_info::NameAndType, and utf8FromConstantPool().
Referenced by buildDispatchTable().
op_invokespecial()
void Interpreter::op_invokespecial () private
Definition at line 1423 of file interpreter.cpp.
References cp_info::class_index, classNameFromConstantPool(), Frame::cls, class_info::constant_pool, cp_info::container, currentFrame(), cp_info::descriptor_index, fetchU2(), frame_stack_, heap_, loader_, cp_info::Methodref, cp_info::name_and_type_index, cp_info::name_index, cp_info::NameAndType, and utf8FromConstantPool().
Referenced by buildDispatchTable().
op_invokestatic()
void Interpreter::op_invokestatic () private
Definition at line 1409 of file interpreter.cpp.
References cp_info::class_index, classNameFromConstantPool(), Frame::cls, class_info::constant_pool, cp_info::container, currentFrame(), cp_info::descriptor_index, fetchU2(), frame_stack_, loader_, cp_info::Methodref, cp_info::name_and_type_index, cp_info::name_index, cp_info::NameAndType, and utf8FromConstantPool().
Referenced by buildDispatchTable().
op_invokevirtual()
void Interpreter::op_invokevirtual () private
Definition at line 1538 of file interpreter.cpp.
References cp_info::class_index, classNameFromConstantPool(), Frame::cls, class_info::constant_pool, cp_info::container, currentFrame(), cp_info::descriptor_index, fetchU2(), frame_stack_, heap_, loader_, cp_info::Methodref, cp_info::name_and_type_index, cp_info::name_index, cp_info::NameAndType, simulatePrint(), and utf8FromConstantPool().
Referenced by buildDispatchTable().
op_ior()
void Interpreter::op_ior () private
Definition at line 804 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_irem()
void Interpreter::op_irem () private
Definition at line 327 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_ireturn()
void Interpreter::op_ireturn () private
Definition at line 374 of file interpreter.cpp.
References frame_stack_.
Referenced by buildDispatchTable().
op_ishl()
void Interpreter::op_ishl () private
Definition at line 818 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_ishr()
void Interpreter::op_ishr () private
Definition at line 826 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_istore()
void Interpreter::op_istore () private
Definition at line 356 of file interpreter.cpp.
References currentFrame(), fetchU1(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_istore_0()
void Interpreter::op_istore_0 () private
Definition at line 351 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_istore_1()
void Interpreter::op_istore_1 () private
Definition at line 352 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_istore_2()
void Interpreter::op_istore_2 () private
Definition at line 353 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_istore_3()
void Interpreter::op_istore_3 () private
Definition at line 354 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_isub()
void Interpreter::op_isub () private
Definition at line 305 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_iushr()
void Interpreter::op_iushr () private
Definition at line 833 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_ixor()
void Interpreter::op_ixor () private
Definition at line 811 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_l2d()
void Interpreter::op_l2d () private
Definition at line 1003 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromDouble(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_l2f()
void Interpreter::op_l2f () private
Definition at line 997 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromFloat(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_l2i()
void Interpreter::op_l2i () private
Definition at line 991 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_ladd()
void Interpreter::op_ladd () private
Definition at line 454 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_laload()
void Interpreter::op_laload () private
Definition at line 1674 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), heap_, Value::i, Frame::pop(), Frame::push(), and Value::ref.
Referenced by buildDispatchTable().
op_land()
void Interpreter::op_land () private
Definition at line 510 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_lastore()
void Interpreter::op_lastore () private
Definition at line 1683 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), heap_, Value::i, Value::l, Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_lcmp()
void Interpreter::op_lcmp () private
Definition at line 674 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_lconst_0()
void Interpreter::op_lconst_0 () private
Definition at line 278 of file interpreter.cpp.
References currentFrame(), Value::fromLong(), and Frame::push().
Referenced by buildDispatchTable().
op_lconst_1()
void Interpreter::op_lconst_1 () private
Definition at line 279 of file interpreter.cpp.
References currentFrame(), Value::fromLong(), and Frame::push().
Referenced by buildDispatchTable().
op_ldc()
void Interpreter::op_ldc () private
Definition at line 386 of file interpreter.cpp.
References cp_info::bytes, Frame::cls, CONSTANT_Float, CONSTANT_Integer, class_info::constant_pool, CONSTANT_String, cp_info::container, currentFrame(), fetchU1(), cp_info::Float, Value::fromFloat(), Value::fromInt(), Value::fromRef(), cp_info::Integer, Frame::push(), and cp_info::tag.
Referenced by buildDispatchTable().
op_ldc2_w()
void Interpreter::op_ldc2_w () private
Definition at line 432 of file interpreter.cpp.
References Frame::cls, CONSTANT_Double, CONSTANT_Long, class_info::constant_pool, cp_info::container, currentFrame(), cp_info::Double, fetchU2(), Value::fromDouble(), Value::fromLong(), cp_info::high_bytes, cp_info::Long, cp_info::low_bytes, Frame::push(), and cp_info::tag.
Referenced by buildDispatchTable().
op_ldc_w()
void Interpreter::op_ldc_w () private
Definition at line 409 of file interpreter.cpp.
References cp_info::bytes, Frame::cls, CONSTANT_Float, CONSTANT_Integer, class_info::constant_pool, CONSTANT_String, cp_info::container, currentFrame(), fetchU2(), cp_info::Float, Value::fromFloat(), Value::fromInt(), Value::fromRef(), cp_info::Integer, Frame::push(), and cp_info::tag.
Referenced by buildDispatchTable().
op_ldiv()
void Interpreter::op_ldiv () private
Definition at line 481 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_lload()
void Interpreter::op_lload () private
Definition at line 753 of file interpreter.cpp.
References currentFrame(), fetchU1(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_lload_0()
void Interpreter::op_lload_0 () private
Definition at line 749 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_lload_1()
void Interpreter::op_lload_1 () private
Definition at line 750 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_lload_2()
void Interpreter::op_lload_2 () private
Definition at line 751 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_lload_3()
void Interpreter::op_lload_3 () private
Definition at line 752 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::push().
Referenced by buildDispatchTable().
op_lmul()
void Interpreter::op_lmul () private
Definition at line 463 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_lneg()
void Interpreter::op_lneg () private
Definition at line 501 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_lookupswitch()
void Interpreter::op_lookupswitch () private
Definition at line 1215 of file interpreter.cpp.
References currentFrame(), Value::data, fetchS4(), Value::i, Frame::pc, and Frame::pop().
Referenced by buildDispatchTable().
op_lor()
void Interpreter::op_lor () private
Definition at line 519 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_lrem()
void Interpreter::op_lrem () private
Definition at line 491 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_lreturn()
void Interpreter::op_lreturn () private
Definition at line 1239 of file interpreter.cpp.
References frame_stack_.
Referenced by buildDispatchTable().
op_lshl()
void Interpreter::op_lshl () private
Definition at line 537 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::i, Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_lshr()
void Interpreter::op_lshr () private
Definition at line 546 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::i, Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_lstore()
void Interpreter::op_lstore () private
Definition at line 777 of file interpreter.cpp.
References currentFrame(), fetchU1(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_lstore_0()
void Interpreter::op_lstore_0 () private
Definition at line 773 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_lstore_1()
void Interpreter::op_lstore_1 () private
Definition at line 774 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_lstore_2()
void Interpreter::op_lstore_2 () private
Definition at line 775 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_lstore_3()
void Interpreter::op_lstore_3 () private
Definition at line 776 of file interpreter.cpp.
References currentFrame(), Frame::locals, and Frame::pop().
Referenced by buildDispatchTable().
op_lsub()
void Interpreter::op_lsub () private
Definition at line 472 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_lushr()
void Interpreter::op_lushr () private
Definition at line 555 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::i, Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_lxor()
void Interpreter::op_lxor () private
Definition at line 528 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromLong(), Value::l, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_new()
void Interpreter::op_new () private
Definition at line 1606 of file interpreter.cpp.
References classNameFromConstantPool(), Frame::cls, currentFrame(), fetchU2(), Value::fromRef(), heap_, loader_, and Frame::push().
Referenced by buildDispatchTable().
op_newarray()
void Interpreter::op_newarray () private
Definition at line 1621 of file interpreter.cpp.
References currentFrame(), Value::data, fetchU1(), Value::fromRef(), heap_, Value::i, Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_nop()
void Interpreter::op_nop () private
Definition at line 260 of file interpreter.cpp.
Referenced by buildDispatchTable().
op_pop()
void Interpreter::op_pop () private
Definition at line 851 of file interpreter.cpp.
References currentFrame(), Frame::pop(), and Frame::top().
Referenced by buildDispatchTable().
op_pop2()
void Interpreter::op_pop2 () private
Definition at line 858 of file interpreter.cpp.
References currentFrame(), and Frame::pop().
Referenced by buildDispatchTable().
op_putfield()
void Interpreter::op_putfield () private
Definition at line 1469 of file interpreter.cpp.
References Frame::cls, class_info::constant_pool, cp_info::container, currentFrame(), Value::data, fetchU2(), cp_info::Fieldref, heap_, cp_info::name_and_type_index, cp_info::name_index, cp_info::NameAndType, Frame::pop(), Value::ref, and utf8FromConstantPool().
Referenced by buildDispatchTable().
op_putstatic()
void Interpreter::op_putstatic () private
Definition at line 1523 of file interpreter.cpp.
References cp_info::class_index, classNameFromConstantPool(), Frame::cls, class_info::constant_pool, cp_info::container, currentFrame(), fetchU2(), cp_info::Fieldref, loader_, cp_info::name_and_type_index, cp_info::name_index, cp_info::NameAndType, Frame::pop(), and utf8FromConstantPool().
Referenced by buildDispatchTable().
op_return()
void Interpreter::op_return () private
Definition at line 369 of file interpreter.cpp.
References frame_stack_.
Referenced by buildDispatchTable().
op_saload()
void Interpreter::op_saload () private
Definition at line 1798 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), heap_, Value::i, Frame::pop(), Frame::push(), and Value::ref.
Referenced by buildDispatchTable().
op_sastore()
void Interpreter::op_sastore () private
Definition at line 1807 of file interpreter.cpp.
References currentFrame(), Value::data, Value::fromInt(), heap_, Value::i, Frame::pop(), and Value::ref.
Referenced by buildDispatchTable().
op_sipush()
void Interpreter::op_sipush () private
Definition at line 293 of file interpreter.cpp.
References currentFrame(), fetchS2(), Value::fromInt(), and Frame::push().
Referenced by buildDispatchTable().
op_swap()
void Interpreter::op_swap () private
Definition at line 932 of file interpreter.cpp.
References currentFrame(), Frame::pop(), and Frame::push().
Referenced by buildDispatchTable().
op_tableswitch()
void Interpreter::op_tableswitch () private
Definition at line 1191 of file interpreter.cpp.
References currentFrame(), Value::data, fetchS4(), Value::i, Frame::pc, and Frame::pop().
Referenced by buildDispatchTable().
run()
void Interpreter::run ()
Definition at line 196 of file interpreter.cpp.
References dispatch_table_, fetchU1(), frame_stack_, and halted_.
Referenced by execute().
simulatePrint()
void Interpreter::simulatePrint (const std::string & method_name, const std::string & descriptor) private
Definition at line 1560 of file interpreter.cpp.
References currentFrame(), Value::d, Value::data, Value::f, Value::i, Value::l, and Frame::pop().
Referenced by op_invokevirtual().
Member Data Documentation
dispatch_table_
std::unordered_map<uint8_t, std::function<void()> > Interpreter::dispatch_table_ private
Definition at line 50 of file interpreter.hpp.
Referenced by buildDispatchTable(), and run().
frame_stack_
FrameStack& Interpreter::frame_stack_ private
Definition at line 41 of file interpreter.hpp.
Referenced by currentFrame(), execute(), Interpreter(), op_areturn(), op_dreturn(), op_freturn(), op_invokeinterface(), op_invokespecial(), op_invokestatic(), op_invokevirtual(), op_ireturn(), op_lreturn(), op_return(), and run().
halted_
bool Interpreter::halted_ = false private
Definition at line 43 of file interpreter.hpp.
Referenced by halt(), halted(), and run().
heap_
Heap& Interpreter::heap_ private
Definition at line 42 of file interpreter.hpp.
Referenced by Interpreter(), op_aaload(), op_aastore(), op_anewarray(), op_arraylength(), op_athrow(), op_baload(), op_bastore(), op_caload(), op_castore(), op_checkcast(), op_daload(), op_dastore(), op_faload(), op_fastore(), op_getfield(), op_iaload(), op_iastore(), op_ifnonnull(), op_ifnull(), op_instanceof(), op_invokeinterface(), op_invokespecial(), op_invokevirtual(), op_laload(), op_lastore(), op_new(), op_newarray(), op_putfield(), op_saload(), and op_sastore().
loader_
ClassLoader& Interpreter::loader_ private
Definition at line 40 of file interpreter.hpp.
Referenced by Interpreter(), op_checkcast(), op_getstatic(), op_instanceof(), op_invokeinterface(), op_invokespecial(), op_invokestatic(), op_invokevirtual(), op_new(), and op_putstatic().
The documentation for this class was generated from the following files:
jvm/interpreter/interpreter.hpp
jvm/interpreter/interpreter.cpp