JVM G3: Parser Class Reference
Parser Class Reference
Motor principal de decodificação (parsing) do arquivo Java.
#include <parser.hpp>
Public Member Functions
Parser (const std::string &filename)
~Parser ()
class_info getClassInfo () const
class_info parse ()
Executa o pipeline completo de extração dos dados sequenciais do bytecode.
Private Member Functions
void parseMagic ()
Valida a assinatura (Magic Number) do arquivo. Todo arquivo compilado para a JVM deve, obrigatoriamente, começar com os bytes 0xCAFEBABE.
void parseMinorVersion ()
void parseMajorVersion ()
void parseConstantPoolCount ()
void parseConstantPool ()
Extrai a Pool de Constantes resolvendo a anomalia do tipo Long/Double. De acordo com a especificação da JVM, variáveis de 64 bits (Long e Double) ocupam dois slots na tabela. O iterador (++i) extra é acionado quando essas tags são encontradas.
void parseAccessFlags ()
void parseThisClass ()
void parseSuperClass ()
void parseInterfacesCount ()
void parseInterfaces ()
void parseFieldsCount ()
void parseFields ()
void parseMethodsCount ()
void parseMethods ()
Lê e estrutura a tabela de métodos, com foco no atributo 'Code'. É o principal da extração lógica: identifica o corpo executável dos métodos e delega a criação das estruturas aninhadas (Exception Table, LineNumberTable, Variables).
void parseAttributesCount ()
void parseAttributes ()
std::string getUtf8Constant (u2 index)
Private Attributes
class_info classInfo
Leitor leitor
Detailed Description
Motor principal de decodificação (parsing) do arquivo Java.
Consome os bytes brutos lidos pela classe Leitor e os distribui rigorosamente de acordo com a Especificação Oficial da JVM (Java Virtual Machine Specification), preenchendo a estrutura 'class_info' (árvore de sintaxe) na memória do C++.
Definition at line 16 of file parser.hpp.
Constructor & Destructor Documentation
Parser()
Parser::Parser (const std::string & filename) explicit
Definition at line 7 of file parser.cpp.
References classInfo, and leitor.
~Parser()
Parser::~Parser () default
Member Function Documentation
getClassInfo()
class_info Parser::getClassInfo () const inline
Definition at line 21 of file parser.hpp.
References classInfo.
getUtf8Constant()
std::string Parser::getUtf8Constant (u2 index) private
Definition at line 269 of file parser.cpp.
References classInfo, CONSTANT_Utf8, cp_info::tag, and cp_info::utf8_str.
Referenced by parseMethods().
parse()
class_info Parser::parse ()
Executa o pipeline completo de extração dos dados sequenciais do bytecode.
Returns
class_info contendo toda a árvore da classe pronta para ser lida e exibida.
Definition at line 11 of file parser.cpp.
References classInfo, parseAccessFlags(), parseAttributes(), parseAttributesCount(), parseConstantPool(), parseConstantPoolCount(), parseFields(), parseFieldsCount(), parseInterfaces(), parseInterfacesCount(), parseMagic(), parseMajorVersion(), parseMethods(), parseMethodsCount(), parseMinorVersion(), parseSuperClass(), and parseThisClass().
Referenced by Exibidor::Exibidor(), and ClassLoader::load().
parseAccessFlags()
void Parser::parseAccessFlags () private
Definition at line 131 of file parser.cpp.
References classInfo, and leitor.
Referenced by parse().
parseAttributes()
void Parser::parseAttributes () private
Definition at line 257 of file parser.cpp.
References attribute_info::attribute_length, attribute_info::attribute_name_index, classInfo, attribute_info::info, and leitor.
Referenced by parse().
parseAttributesCount()
void Parser::parseAttributesCount () private
Definition at line 252 of file parser.cpp.
References classInfo, and leitor.
Referenced by parse().
parseConstantPool()
void Parser::parseConstantPool () private
Extrai a Pool de Constantes resolvendo a anomalia do tipo Long/Double. De acordo com a especificação da JVM, variáveis de 64 bits (Long e Double) ocupam dois slots na tabela. O iterador (++i) extra é acionado quando essas tags são encontradas.
Definition at line 66 of file parser.cpp.
References cp_info::bootstrap_method_attr_index, cp_info::bytes, cp_info::Class, cp_info::class_index, classInfo, CONSTANT_Class, CONSTANT_Double, CONSTANT_Fieldref, CONSTANT_Float, CONSTANT_Integer, CONSTANT_InterfaceMethodref, CONSTANT_InvokeDynamic, CONSTANT_Long, CONSTANT_MethodHandle, CONSTANT_Methodref, CONSTANT_MethodType, CONSTANT_Module, CONSTANT_NameAndType, CONSTANT_Package, CONSTANT_String, CONSTANT_Utf8, cp_info::container, cp_info::descriptor_index, cp_info::Fieldref, cp_info::high_bytes, cp_info::Integer, cp_info::InvokeDynamic, leitor, cp_info::Long, cp_info::low_bytes, cp_info::MethodHandle, cp_info::MethodType, cp_info::name_and_type_index, cp_info::name_index, cp_info::NameAndType, cp_info::reference_index, cp_info::reference_kind, cp_info::String, cp_info::string_index, cp_info::tag, and cp_info::utf8_str.
Referenced by parse().
parseConstantPoolCount()
void Parser::parseConstantPoolCount () private
Definition at line 56 of file parser.cpp.
References classInfo, and leitor.
Referenced by parse().
parseFields()
void Parser::parseFields () private
Definition at line 165 of file parser.cpp.
References field_info::access_flags, attribute_info::attribute_length, attribute_info::attribute_name_index, field_info::attributes, field_info::attributes_count, classInfo, field_info::descriptor_index, attribute_info::info, leitor, and field_info::name_index.
Referenced by parse().
parseFieldsCount()
void Parser::parseFieldsCount () private
Definition at line 160 of file parser.cpp.
References classInfo, and leitor.
Referenced by parse().
parseInterfaces()
void Parser::parseInterfaces () private
Definition at line 151 of file parser.cpp.
References classInfo, and leitor.
Referenced by parse().
parseInterfacesCount()
void Parser::parseInterfacesCount () private
Definition at line 146 of file parser.cpp.
References classInfo, and leitor.
Referenced by parse().
parseMagic()
void Parser::parseMagic () private
Valida a assinatura (Magic Number) do arquivo. Todo arquivo compilado para a JVM deve, obrigatoriamente, começar com os bytes 0xCAFEBABE.
Definition at line 36 of file parser.cpp.
References classInfo, and leitor.
Referenced by parse().
parseMajorVersion()
void Parser::parseMajorVersion () private
Definition at line 51 of file parser.cpp.
References classInfo, and leitor.
Referenced by parse().
parseMethods()
void Parser::parseMethods () private
Lê e estrutura a tabela de métodos, com foco no atributo 'Code'. É o principal da extração lógica: identifica o corpo executável dos métodos e delega a criação das estruturas aninhadas (Exception Table, LineNumberTable, Variables).
Definition at line 197 of file parser.cpp.
References method_info::access_flags, attribute_info::attribute_length, attribute_info::attribute_name_index, method_info::attributes, method_info::attributes_count, classInfo, attribute_info::code_data, method_info::descriptor_index, getUtf8Constant(), attribute_info::info, leitor, and method_info::name_index.
Referenced by parse().
parseMethodsCount()
void Parser::parseMethodsCount () private
Definition at line 187 of file parser.cpp.
References classInfo, and leitor.
Referenced by parse().
parseMinorVersion()
void Parser::parseMinorVersion () private
Definition at line 46 of file parser.cpp.
References classInfo, and leitor.
Referenced by parse().
parseSuperClass()
void Parser::parseSuperClass () private
Definition at line 141 of file parser.cpp.
References classInfo, and leitor.
Referenced by parse().
parseThisClass()
void Parser::parseThisClass () private
Definition at line 136 of file parser.cpp.
References classInfo, and leitor.
Referenced by parse().
Member Data Documentation
classInfo
class_info Parser::classInfo private
Definition at line 30 of file parser.hpp.
Referenced by getClassInfo(), getUtf8Constant(), parse(), parseAccessFlags(), parseAttributes(), parseAttributesCount(), parseConstantPool(), parseConstantPoolCount(), parseFields(), parseFieldsCount(), parseInterfaces(), parseInterfacesCount(), parseMagic(), parseMajorVersion(), parseMethods(), parseMethodsCount(), parseMinorVersion(), Parser(), parseSuperClass(), and parseThisClass().
leitor
Leitor Parser::leitor private
Definition at line 31 of file parser.hpp.
Referenced by parseAccessFlags(), parseAttributes(), parseAttributesCount(), parseConstantPool(), parseConstantPoolCount(), parseFields(), parseFieldsCount(), parseInterfaces(), parseInterfacesCount(), parseMagic(), parseMajorVersion(), parseMethods(), parseMethodsCount(), parseMinorVersion(), Parser(), parseSuperClass(), and parseThisClass().
The documentation for this class was generated from the following files:
jvm/parser/parser.hpp
jvm/parser/parser.cpp