JVM G3: Exibidor Class Reference
Exibidor Class Reference
Responsável por formatar e imprimir as informações da classe.
#include <exibidor.hpp>
Public Member Functions
Exibidor (const std::string &filename)
~Exibidor ()
void display ()
Função orquestradora que chama todas as rotinas de exibição em tela no terminal.
Private Member Functions
void constantPoolDisplay ()
Itera sobre a Pool de Constantes imprimindo valores.
void fieldsDisplay ()
Exibe os campos (variáveis) da classe e seus atributos específicos.
void methodsDisplay ()
Exibe informações a nível de Método e processa seus atributos.
void attributesDisplay ()
Exibe os atributos em nível de Classe.
std::pair< std::string, std::string > getMethodSignature (const method_info &method)
Traduz as strings difíceis da JVM para uma assinatura de método Java tradicional.
Private Attributes
std::string filename
class_info classInfo
Detailed Description
Responsável por formatar e imprimir as informações da classe.
Realiza a ponte entre os metadados brutos armazenados (ex: números hexadecimais) e a representação legível para humanos, fazendo ligações dinâmicas com a Constant Pool para exibir os nomes reais de classes, métodos e variáveis referenciadas no código.
Definition at line 19 of file exibidor.hpp.
Constructor & Destructor Documentation
Exibidor()
Exibidor::Exibidor (const std::string & filename) explicit
Definition at line 23 of file exibidor.cpp.
References classInfo, filename, and Parser::parse().
~Exibidor()
Exibidor::~Exibidor () default
Member Function Documentation
attributesDisplay()
void Exibidor::attributesDisplay () private
Exibe os atributos em nível de Classe.
Processa metadados gerais que afetam a classe como um todo, tais como arquivo de origem (SourceFile), classes internas (InnerClasses) e métodos de inicialização dinâmica (BootstrapMethods para invokedynamic).
Definition at line 395 of file exibidor.cpp.
References attribute_info::attribute_length, attribute_info::attribute_name_index, classInfo, cpEntryComment(), getClassAccessFlagsString(), attribute_info::info, nameAndTypeStr(), readU2(), and utf8FromConstantPool().
Referenced by display().
constantPoolDisplay()
void Exibidor::constantPoolDisplay () private
Itera sobre a Pool de Constantes imprimindo valores.
Lógica Crítica: As chamadas cpEntryComment() são essenciais aqui porque procuram os índices de referência de forma recursiva e retornam o nome final real atrelado à constante.
Definition at line 78 of file exibidor.cpp.
References cp_info::bootstrap_method_attr_index, cp_info::bytes, cp_info::Class, cp_info::class_index, classInfo, CONSTANT_Class, CONSTANT_Double, CONSTANT_Fieldref, CONSTANT_Float, CONSTANT_Integer, CONSTANT_InterfaceMethodref, CONSTANT_InvokeDynamic, CONSTANT_Long, CONSTANT_MethodHandle, CONSTANT_Methodref, CONSTANT_MethodType, CONSTANT_Module, CONSTANT_NameAndType, CONSTANT_Package, CONSTANT_String, CONSTANT_Utf8, cp_info::container, cpEntryComment(), cp_info::descriptor_index, cp_info::Double, cp_info::Fieldref, cp_info::Float, cp_info::high_bytes, cp_info::Integer, cp_info::InterfaceMethodref, cp_info::InvokeDynamic, cp_info::Long, cp_info::low_bytes, cp_info::MethodHandle, cp_info::Methodref, cp_info::MethodType, cp_info::name_and_type_index, cp_info::name_index, cp_info::NameAndType, cp_info::reference_index, cp_info::reference_kind, cp_info::String, cp_info::string_index, cp_info::tag, and cp_info::utf8_str.
Referenced by display().
display()
void Exibidor::display ()
Função orquestradora que chama todas as rotinas de exibição em tela no terminal.
Definition at line 31 of file exibidor.cpp.
References attributesDisplay(), classInfo, classNameFromConstantPool(), constantPoolDisplay(), fieldsDisplay(), filename, getClassAccessFlagsString(), and methodsDisplay().
Referenced by main().
fieldsDisplay()
void Exibidor::fieldsDisplay () private
Exibe os campos (variáveis) da classe e seus atributos específicos.
Formata o tipo da variável, modificadores de acesso e processa atributos associados ao campo, como ConstantValue (para primitivos final) e Anotações.
Definition at line 199 of file exibidor.cpp.
References field_info::access_flags, attribute_info::attribute_name_index, field_info::attributes, field_info::attributes_count, classInfo, cpEntryComment(), field_info::descriptor_index, formatFieldType(), getFieldAccessFlagsString(), attribute_info::info, field_info::name_index, readU2(), and utf8FromConstantPool().
Referenced by display().
getMethodSignature()
std::pair< string, string > Exibidor::getMethodSignature (const method_info & method) private
Traduz as strings difíceis da JVM para uma assinatura de método Java tradicional.
Definition at line 382 of file exibidor.cpp.
References classInfo, method_info::descriptor_index, formatMethodParameters(), formatMethodReturnType(), and utf8FromConstantPool().
Referenced by methodsDisplay().
methodsDisplay()
void Exibidor::methodsDisplay () private
Exibe informações a nível de Método e processa seus atributos.
Dentro desta função ocorre a chamada disassembleCode(), que entra profundamente no atributo 'Code' para traduzir o array de bytes em instruções assembly da JVM (Mnemônicos), além de exibir as Exception Tables e Line Number Tables relativas ao método em questão.
Definition at line 252 of file exibidor.cpp.
References method_info::access_flags, attribute_info::attribute_name_index, code_attribute::attributes, method_info::attributes, code_attribute::attributes_count, method_info::attributes_count, classInfo, classNameFromConstantPool(), code_attribute::code, attribute_info::code_data, code_attribute::code_length, disassembleCode(), code_attribute::exception_table, code_attribute::exception_table_length, getMethodAccessFlagsString(), getMethodSignature(), attribute_info::info, code_attribute::max_locals, code_attribute::max_stack, method_info::name_index, and utf8FromConstantPool().
Referenced by display().
Member Data Documentation
classInfo
class_info Exibidor::classInfo private
Definition at line 31 of file exibidor.hpp.
Referenced by attributesDisplay(), constantPoolDisplay(), display(), Exibidor(), fieldsDisplay(), getMethodSignature(), and methodsDisplay().
filename
std::string Exibidor::filename private
Definition at line 30 of file exibidor.hpp.
Referenced by display(), and Exibidor().
The documentation for this class was generated from the following files:
jvm/exibidor/exibidor.hpp
jvm/exibidor/exibidor.cpp