JVM G3: jvm/common/cp_utils.hpp File Reference
cp_utils.hpp File Reference
#include <string>
#include <stdexcept>
#include <cstring>
#include "estrutura_dados.hpp"
#include "constants.hpp"
#include "bytecode_utils.hpp"
Functions
std::string utf8FromConstantPool (const class_info &info, u2 index)
Extrator de Strings Utf8 puras da Constant Pool.
std::string classNameFromConstantPool (const class_info &info, u2 index)
Resolve o nome de uma Classe.
std::string nameAndTypeStr (const class_info &info, u2 index)
Resolve assinaturas de NameAndType.
std::string cpEntryComment (const class_info &info, u2 index)
Função central de resolução recursiva da Constant Pool.
const method_info * findMethod (const class_info &cls, const std::string &name, const std::string &descriptor)
const field_info * findField (const class_info &cls, const std::string &name, const std::string &descriptor)
Function Documentation
classNameFromConstantPool()
std::string classNameFromConstantPool (const class_info & info, u2 index) inline
Resolve o nome de uma Classe.
Um CONSTANT_Class não contém a string com o nome da classe; ele contém um índice que aponta para um CONSTANT_Utf8. Esta função faz esse salto automático.
Definition at line 36 of file cp_utils.hpp.
References cp_info::Class, CONSTANT_Class, class_info::constant_pool, cp_info::container, cp_info::name_index, cp_info::tag, and utf8FromConstantPool().
Referenced by cpEntryComment(), Exibidor::display(), Exibidor::methodsDisplay(), Interpreter::op_anewarray(), Interpreter::op_checkcast(), Interpreter::op_getstatic(), Interpreter::op_instanceof(), Interpreter::op_invokeinterface(), Interpreter::op_invokespecial(), Interpreter::op_invokestatic(), Interpreter::op_invokevirtual(), Interpreter::op_new(), and Interpreter::op_putstatic().
cpEntryComment()
std::string cpEntryComment (const class_info & info, u2 index) inline
Função central de resolução recursiva da Constant Pool.
É o coração da formatação de referências. Dado qualquer índice, ela descobre seu tipo, segue a cadeia de ponteiros e retorna uma representação legível (comentário) para ser exibida ao lado da constante bruta (ex: java/lang/Object.<init>:()V).
Definition at line 70 of file cp_utils.hpp.
References cp_info::bootstrap_method_attr_index, cp_info::bytes, cp_info::Class, cp_info::class_index, classNameFromConstantPool(), CONSTANT_Class, CONSTANT_Double, CONSTANT_Fieldref, CONSTANT_Float, CONSTANT_Integer, CONSTANT_InterfaceMethodref, CONSTANT_InvokeDynamic, CONSTANT_Long, CONSTANT_MethodHandle, CONSTANT_Methodref, CONSTANT_MethodType, CONSTANT_Module, CONSTANT_NameAndType, CONSTANT_Package, class_info::constant_pool, CONSTANT_String, cp_info::container, cpEntryComment(), cp_info::descriptor_index, cp_info::Double, cp_info::Fieldref, cp_info::Float, cp_info::high_bytes, cp_info::Integer, cp_info::InvokeDynamic, cp_info::Long, cp_info::low_bytes, cp_info::MethodHandle, cp_info::MethodType, cp_info::name_and_type_index, cp_info::name_index, nameAndTypeStr(), cp_info::reference_index, cp_info::reference_kind, cp_info::String, cp_info::string_index, cp_info::tag, and utf8FromConstantPool().
Referenced by Exibidor::attributesDisplay(), Exibidor::constantPoolDisplay(), cpEntryComment(), disassembleCode(), and Exibidor::fieldsDisplay().
findField()
const field_info * findField (const class_info & cls, const std::string & name, const std::string & descriptor) inline
Definition at line 157 of file cp_utils.hpp.
References field_info::descriptor_index, class_info::fields, field_info::name_index, and utf8FromConstantPool().
findMethod()
const method_info * findMethod (const class_info & cls, const std::string & name, const std::string & descriptor) inline
Definition at line 146 of file cp_utils.hpp.
References method_info::descriptor_index, class_info::methods, method_info::name_index, and utf8FromConstantPool().
Referenced by main().
nameAndTypeStr()
std::string nameAndTypeStr (const class_info & info, u2 index) inline
Resolve assinaturas de NameAndType.
Une o nome (ex: "println") e o descritor (ex: "(Ljava/lang/String;)V") separando-os por dois pontos, auxiliando na formatação final de métodos e campos.
Definition at line 54 of file cp_utils.hpp.
References CONSTANT_NameAndType, class_info::constant_pool, cp_info::container, cp_info::descriptor_index, cp_info::name_index, cp_info::NameAndType, cp_info::tag, and utf8FromConstantPool().
Referenced by Exibidor::attributesDisplay(), and cpEntryComment().
utf8FromConstantPool()
std::string utf8FromConstantPool (const class_info & info, u2 index) inline
Extrator de Strings Utf8 puras da Constant Pool.
Verifica se o índice é válido e se a tag realmente aponta para um CONSTANT_Utf8, retornando a string C++ correspondente. Lança exceções caso o arquivo .class tente referenciar índices inválidos.
Definition at line 18 of file cp_utils.hpp.
References class_info::constant_pool, CONSTANT_Utf8, cp_info::tag, and cp_info::utf8_str.
Referenced by Exibidor::attributesDisplay(), classNameFromConstantPool(), cpEntryComment(), Exibidor::fieldsDisplay(), findField(), findMethod(), Exibidor::getMethodSignature(), Exibidor::methodsDisplay(), nameAndTypeStr(), Interpreter::op_getfield(), Interpreter::op_getstatic(), Interpreter::op_invokeinterface(), Interpreter::op_invokespecial(), Interpreter::op_invokestatic(), Interpreter::op_invokevirtual(), Interpreter::op_putfield(), and Interpreter::op_putstatic().