JVM G3: jvm/common/descriptor.hpp File Reference
descriptor.hpp File Reference
#include <string>
#include <stdexcept>
Functions
std::string parseTypeDescriptor (const std::string &descriptor, size_t &position)
Tradutor de Descritores de Tipo da JVM.
std::string formatMethodParameters (const std::string &descriptor)
Extrai e formata os parâmetros de um método.
std::string formatMethodReturnType (const std::string &descriptor)
Extrai e formata o tipo de retorno de um método.
std::string formatFieldType (const std::string &descriptor)
Function Documentation
formatFieldType()
std::string formatFieldType (const std::string & descriptor) inline
Definition at line 101 of file descriptor.hpp.
References parseTypeDescriptor().
Referenced by Exibidor::fieldsDisplay().
formatMethodParameters()
std::string formatMethodParameters (const std::string & descriptor) inline
Extrai e formata os parâmetros de um método.
Isola tudo o que está dentro dos parênteses '(...)' do descritor e itera traduzindo tipo por tipo, separando-os por vírgula.
Definition at line 64 of file descriptor.hpp.
References parseTypeDescriptor().
Referenced by Exibidor::getMethodSignature().
formatMethodReturnType()
std::string formatMethodReturnType (const std::string & descriptor) inline
Extrai e formata o tipo de retorno de um método.
Isola e traduz a parte do descritor que vem logo após o parêntese final ')'.
Definition at line 91 of file descriptor.hpp.
References parseTypeDescriptor().
Referenced by Exibidor::getMethodSignature().
parseTypeDescriptor()
std::string parseTypeDescriptor (const std::string & descriptor, size_t & position) inline
Tradutor de Descritores de Tipo da JVM.
A JVM usa códigos compactos para tipos (ex: 'I' para int, 'Z' para boolean, '[Ljava/lang/String;' para String[]). Esta função percorre essa string codificada e a converte para a sintaxe real da linguagem Java legível para humanos.
Definition at line 14 of file descriptor.hpp.
Referenced by formatFieldType(), formatMethodParameters(), and formatMethodReturnType().