JVM G3: jvm/exibidor/disasm.cpp File Reference
disasm.cpp File Reference
#include "disasm.hpp"
#include "bytecode_utils.hpp"
#include "cp_utils.hpp"
#include <iostream>
#include <iomanip>
#include <stdexcept>
Functions
void disassembleCode (const std::vector< u1 > &code, u4 code_length, const class_info &cls)
O loop principal do interpretador de Bytecode (Disassembler).
Function Documentation
disassembleCode()
void disassembleCode (const std::vector< u1 > & code, u4 code_length, const class_info & cls)
O loop principal do interpretador de Bytecode (Disassembler).
Motor de decodificação de Bytecodes (Disassembler).
Percorre o array de bytes instrução por instrução, mantendo um Program Counter (pc). Decodifica o opcode (switch principal), consome a quantidade correta de operandos e formata o assembly do Java com as devidas referências e saltos calculados matematicamente.
O loop principal do interpretador de Bytecode (Disassembler).
Traduz o array de bytes bruto do atributo 'Code' em instruções assembly legíveis da JVM (mnemônicos como aload_0, invokespecial). Resolve offsets de pulo (branching) e lida com instruções avançadas de tamanho variável (como tableswitch e lookupswitch).
Definition at line 29 of file disasm.cpp.
References cpEntryComment(), readS2(), readS4(), and readU2().
Referenced by Exibidor::methodsDisplay().