JVM G3: Frame Struct Reference
Frame Struct Reference
#include <runtime.hpp>
Public Member Functions
void push (Value v)
Value pop ()
Value & top ()
Public Attributes
std::vector< Value > locals
std::stack< Value > operand_stack
const class_info * cls
const method_info * method
const code_attribute * code
size_t pc
Detailed Description
Definition at line 46 of file runtime.hpp.
Member Function Documentation
pop()
Value Frame::pop () inline
Definition at line 58 of file runtime.hpp.
References operand_stack.
Referenced by Interpreter::op_aaload(), Interpreter::op_aastore(), Interpreter::op_anewarray(), Interpreter::op_arraylength(), Interpreter::op_astore(), Interpreter::op_astore_0(), Interpreter::op_astore_1(), Interpreter::op_astore_2(), Interpreter::op_astore_3(), Interpreter::op_athrow(), Interpreter::op_baload(), Interpreter::op_bastore(), Interpreter::op_caload(), Interpreter::op_castore(), Interpreter::op_d2f(), Interpreter::op_d2i(), Interpreter::op_d2l(), Interpreter::op_dadd(), Interpreter::op_daload(), Interpreter::op_dastore(), Interpreter::op_dcmpg(), Interpreter::op_dcmpl(), Interpreter::op_ddiv(), Interpreter::op_dmul(), Interpreter::op_dneg(), Interpreter::op_drem(), Interpreter::op_dstore(), Interpreter::op_dstore_0(), Interpreter::op_dstore_1(), Interpreter::op_dstore_2(), Interpreter::op_dstore_3(), Interpreter::op_dsub(), Interpreter::op_dup2(), Interpreter::op_dup_x1(), Interpreter::op_dup_x2(), Interpreter::op_f2d(), Interpreter::op_f2i(), Interpreter::op_f2l(), Interpreter::op_fadd(), Interpreter::op_faload(), Interpreter::op_fastore(), Interpreter::op_fcmpg(), Interpreter::op_fcmpl(), Interpreter::op_fdiv(), Interpreter::op_fmul(), Interpreter::op_fneg(), Interpreter::op_frem(), Interpreter::op_fstore(), Interpreter::op_fstore_0(), Interpreter::op_fstore_1(), Interpreter::op_fstore_2(), Interpreter::op_fstore_3(), Interpreter::op_fsub(), Interpreter::op_getfield(), Interpreter::op_i2b(), Interpreter::op_i2c(), Interpreter::op_i2d(), Interpreter::op_i2f(), Interpreter::op_i2l(), Interpreter::op_i2s(), Interpreter::op_iadd(), Interpreter::op_iaload(), Interpreter::op_iand(), Interpreter::op_iastore(), Interpreter::op_idiv(), Interpreter::op_if_acmpeq(), Interpreter::op_if_acmpne(), Interpreter::op_if_icmpeq(), Interpreter::op_if_icmpge(), Interpreter::op_if_icmpgt(), Interpreter::op_if_icmple(), Interpreter::op_if_icmplt(), Interpreter::op_if_icmpne(), Interpreter::op_ifeq(), Interpreter::op_ifge(), Interpreter::op_ifgt(), Interpreter::op_ifle(), Interpreter::op_iflt(), Interpreter::op_ifne(), Interpreter::op_ifnonnull(), Interpreter::op_ifnull(), Interpreter::op_imul(), Interpreter::op_ineg(), Interpreter::op_instanceof(), Interpreter::op_ior(), Interpreter::op_irem(), Interpreter::op_ishl(), Interpreter::op_ishr(), Interpreter::op_istore(), Interpreter::op_istore_0(), Interpreter::op_istore_1(), Interpreter::op_istore_2(), Interpreter::op_istore_3(), Interpreter::op_isub(), Interpreter::op_iushr(), Interpreter::op_ixor(), Interpreter::op_l2d(), Interpreter::op_l2f(), Interpreter::op_l2i(), Interpreter::op_ladd(), Interpreter::op_laload(), Interpreter::op_land(), Interpreter::op_lastore(), Interpreter::op_lcmp(), Interpreter::op_ldiv(), Interpreter::op_lmul(), Interpreter::op_lneg(), Interpreter::op_lookupswitch(), Interpreter::op_lor(), Interpreter::op_lrem(), Interpreter::op_lshl(), Interpreter::op_lshr(), Interpreter::op_lstore(), Interpreter::op_lstore_0(), Interpreter::op_lstore_1(), Interpreter::op_lstore_2(), Interpreter::op_lstore_3(), Interpreter::op_lsub(), Interpreter::op_lushr(), Interpreter::op_lxor(), Interpreter::op_newarray(), Interpreter::op_pop(), Interpreter::op_pop2(), Interpreter::op_putfield(), Interpreter::op_putstatic(), Interpreter::op_saload(), Interpreter::op_sastore(), Interpreter::op_swap(), Interpreter::op_tableswitch(), and Interpreter::simulatePrint().
push()
void Frame::push (Value v) inline
Definition at line 54 of file runtime.hpp.
References operand_stack.
Referenced by Interpreter::op_aaload(), Interpreter::op_aconst_null(), Interpreter::op_aload(), Interpreter::op_aload_0(), Interpreter::op_aload_1(), Interpreter::op_aload_2(), Interpreter::op_aload_3(), Interpreter::op_anewarray(), Interpreter::op_arraylength(), Interpreter::op_baload(), Interpreter::op_bipush(), Interpreter::op_caload(), Interpreter::op_d2f(), Interpreter::op_d2i(), Interpreter::op_d2l(), Interpreter::op_dadd(), Interpreter::op_daload(), Interpreter::op_dcmpg(), Interpreter::op_dcmpl(), Interpreter::op_dconst_0(), Interpreter::op_dconst_1(), Interpreter::op_ddiv(), Interpreter::op_dload(), Interpreter::op_dload_0(), Interpreter::op_dload_1(), Interpreter::op_dload_2(), Interpreter::op_dload_3(), Interpreter::op_dmul(), Interpreter::op_dneg(), Interpreter::op_drem(), Interpreter::op_dsub(), Interpreter::op_dup(), Interpreter::op_dup2(), Interpreter::op_dup_x1(), Interpreter::op_dup_x2(), Interpreter::op_f2d(), Interpreter::op_f2i(), Interpreter::op_f2l(), Interpreter::op_fadd(), Interpreter::op_faload(), Interpreter::op_fcmpg(), Interpreter::op_fcmpl(), Interpreter::op_fconst_0(), Interpreter::op_fconst_1(), Interpreter::op_fconst_2(), Interpreter::op_fdiv(), Interpreter::op_fload(), Interpreter::op_fload_0(), Interpreter::op_fload_1(), Interpreter::op_fload_2(), Interpreter::op_fload_3(), Interpreter::op_fmul(), Interpreter::op_fneg(), Interpreter::op_frem(), Interpreter::op_fsub(), Interpreter::op_getfield(), Interpreter::op_getstatic(), Interpreter::op_i2b(), Interpreter::op_i2c(), Interpreter::op_i2d(), Interpreter::op_i2f(), Interpreter::op_i2l(), Interpreter::op_i2s(), Interpreter::op_iadd(), Interpreter::op_iaload(), Interpreter::op_iand(), Interpreter::op_iconst(), Interpreter::op_idiv(), Interpreter::op_iload(), Interpreter::op_iload_0(), Interpreter::op_iload_1(), Interpreter::op_iload_2(), Interpreter::op_iload_3(), Interpreter::op_imul(), Interpreter::op_ineg(), Interpreter::op_instanceof(), Interpreter::op_ior(), Interpreter::op_irem(), Interpreter::op_ishl(), Interpreter::op_ishr(), Interpreter::op_isub(), Interpreter::op_iushr(), Interpreter::op_ixor(), Interpreter::op_l2d(), Interpreter::op_l2f(), Interpreter::op_l2i(), Interpreter::op_ladd(), Interpreter::op_laload(), Interpreter::op_land(), Interpreter::op_lcmp(), Interpreter::op_lconst_0(), Interpreter::op_lconst_1(), Interpreter::op_ldc(), Interpreter::op_ldc2_w(), Interpreter::op_ldc_w(), Interpreter::op_ldiv(), Interpreter::op_lload(), Interpreter::op_lload_0(), Interpreter::op_lload_1(), Interpreter::op_lload_2(), Interpreter::op_lload_3(), Interpreter::op_lmul(), Interpreter::op_lneg(), Interpreter::op_lor(), Interpreter::op_lrem(), Interpreter::op_lshl(), Interpreter::op_lshr(), Interpreter::op_lsub(), Interpreter::op_lushr(), Interpreter::op_lxor(), Interpreter::op_new(), Interpreter::op_newarray(), Interpreter::op_saload(), Interpreter::op_sipush(), and Interpreter::op_swap().
top()
Value & Frame::top () inline
Definition at line 66 of file runtime.hpp.
References operand_stack.
Referenced by Interpreter::op_checkcast(), Interpreter::op_dup(), and Interpreter::op_pop().
Member Data Documentation
cls
const class_info* Frame::cls
Definition at line 49 of file runtime.hpp.
Referenced by Interpreter::execute(), Interpreter::op_anewarray(), Interpreter::op_checkcast(), Interpreter::op_getfield(), Interpreter::op_getstatic(), Interpreter::op_instanceof(), Interpreter::op_invokeinterface(), Interpreter::op_invokespecial(), Interpreter::op_invokestatic(), Interpreter::op_invokevirtual(), Interpreter::op_ldc(), Interpreter::op_ldc2_w(), Interpreter::op_ldc_w(), Interpreter::op_new(), Interpreter::op_putfield(), and Interpreter::op_putstatic().
code
const code_attribute* Frame::code
Definition at line 51 of file runtime.hpp.
Referenced by Interpreter::execute(), and Interpreter::fetchU1().
locals
std::vector<Value> Frame::locals
Definition at line 47 of file runtime.hpp.
Referenced by Interpreter::execute(), Interpreter::op_aload(), Interpreter::op_aload_0(), Interpreter::op_aload_1(), Interpreter::op_aload_2(), Interpreter::op_aload_3(), Interpreter::op_astore(), Interpreter::op_astore_0(), Interpreter::op_astore_1(), Interpreter::op_astore_2(), Interpreter::op_astore_3(), Interpreter::op_dload(), Interpreter::op_dload_0(), Interpreter::op_dload_1(), Interpreter::op_dload_2(), Interpreter::op_dload_3(), Interpreter::op_dstore(), Interpreter::op_dstore_0(), Interpreter::op_dstore_1(), Interpreter::op_dstore_2(), Interpreter::op_dstore_3(), Interpreter::op_fload(), Interpreter::op_fload_0(), Interpreter::op_fload_1(), Interpreter::op_fload_2(), Interpreter::op_fload_3(), Interpreter::op_fstore(), Interpreter::op_fstore_0(), Interpreter::op_fstore_1(), Interpreter::op_fstore_2(), Interpreter::op_fstore_3(), Interpreter::op_iinc(), Interpreter::op_iload(), Interpreter::op_iload_0(), Interpreter::op_iload_1(), Interpreter::op_iload_2(), Interpreter::op_iload_3(), Interpreter::op_istore(), Interpreter::op_istore_0(), Interpreter::op_istore_1(), Interpreter::op_istore_2(), Interpreter::op_istore_3(), Interpreter::op_lload(), Interpreter::op_lload_0(), Interpreter::op_lload_1(), Interpreter::op_lload_2(), Interpreter::op_lload_3(), Interpreter::op_lstore(), Interpreter::op_lstore_0(), Interpreter::op_lstore_1(), Interpreter::op_lstore_2(), and Interpreter::op_lstore_3().
method
const method_info* Frame::method
Definition at line 50 of file runtime.hpp.
Referenced by Interpreter::execute().
operand_stack
std::stack<Value> Frame::operand_stack
Definition at line 48 of file runtime.hpp.
Referenced by pop(), push(), and top().
pc
size_t Frame::pc
Definition at line 52 of file runtime.hpp.
Referenced by Interpreter::branch(), Interpreter::execute(), Interpreter::fetchU1(), Interpreter::op_goto(), Interpreter::op_goto_w(), Interpreter::op_lookupswitch(), and Interpreter::op_tableswitch().
The documentation for this struct was generated from the following file:
jvm/runtime/runtime.hpp